# Base DreamerV3 Configuration
# This contains the core parameters that are shared across all experiments

defaults:
  # Environment
  task: 'vizdoom_basic'
  envs: 32
  action_repeat: 1
  time_limit: 0
  prefill: 2500
  eval_every: 1e4
  eval_episode_num: 10
  log_every: 1e4
  reset_every: 0
  device: 'cuda:0'
  compile: False
  precision: 32
  
  # Training
  batch_size: 16
  batch_length: 64
  train_ratio: 512
  pretrain: 100
  model_lr: 3e-4
  opt_eps: 1e-5
  grad_clip: 100.0
  weight_decay: 1e-6
  opt: 'adam'
  
  # World Model - Base parameters (will be overridden by specific configs)
  dyn_hidden: 512
  dyn_deter: 512
  dyn_stoch: 32
  dyn_discrete: 32
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  unimix_ratio: 0.01
  initial: 'learned'
  
  # Hierarchical parameters (disabled by default)
  hierarchical_mode: false
  dyn_stoch_top: 16
  dyn_stoch_bottom: 16
  dyn_discrete_top: 32
  dyn_discrete_bottom: 32
  
  # Architecture
  units: 512
  act: 'SiLU'
  norm: True
  
  # Encoder/Decoder
  encoder:
    mlp_keys: '$^'
    cnn_keys: 'image'
    act: 'SiLU'
    norm: True
    cnn_depth: 32
    kernel_size: 4
    minres: 4
    mlp_layers: 5
    mlp_units: 1024
    symlog_inputs: True
    
  decoder:
    mlp_keys: '$^'
    cnn_keys: 'image'
    act: 'SiLU'
    norm: True
    cnn_depth: 32
    kernel_size: 4
    minres: 4
    mlp_layers: 5
    mlp_units: 1024
    cnn_sigmoid: False
    image_dist: 'mse'
    vector_dist: 'symlog_mse'
    outscale: 1.0
    
  # Actor-Critic
  actor:
    layers: 2
    dist: 'normal'
    entropy: 3e-4
    unimix_ratio: 0.01
    std: 'learned'
    min_std: 0.1
    max_std: 1.0
    temp: 0.1
    lr: 3e-5
    eps: 1e-5
    grad_clip: 100.0
    outscale: 1.0
    
  critic:
    layers: 2
    dist: 'symlog_disc'
    slow_target: True
    lr: 3e-5
    eps: 1e-5
    grad_clip: 100.0
    outscale: 1.0
    
  # Loss scales
  reward_head:
    layers: 2
    dist: 'symlog_mse'
    outscale: 1.0
    loss_scale: 1.0
    
  cont_head:
    layers: 2
    outscale: 1.0
    loss_scale: 1.0
    
  # Imagination
  imag_horizon: 15
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.1
  
  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  
  # Logging
  grad_heads: ['decoder', 'reward', 'cont']
  reward_EMA: True
  
  # Misc
  discount: 0.997
  lambda_: 0.95
  horizon: 333
